eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: clientName
    prefer-ip-address: true
spring:
  application:
    name: eurekaClient1
server:
  port: 8762
